package org.kseco.database;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.LinkedHashSet;
import java.util.Locale;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;

/** Small portable-DDL boundary for ks-Eco business and settlement tables. */
public final class BusinessSchemaDialect {
    private static final Pattern IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");

    private BusinessSchemaDialect() { }

    public static DatabaseDialect detect(Connection connection) throws SQLException {
        return DatabaseDialect.detect(Objects.requireNonNull(connection, "connection"));
    }

    public static String floatingPointType(DatabaseDialect dialect) {
        return dialect == DatabaseDialect.POSTGRESQL ? "DOUBLE PRECISION" : "DOUBLE";
    }

    public static String binaryType(DatabaseDialect dialect) {
        return dialect == DatabaseDialect.POSTGRESQL ? "BYTEA" : "BLOB";
    }

    public static String identityPrimaryKey(DatabaseDialect dialect) {
        return switch (Objects.requireNonNull(dialect, "dialect")) {
            case SQLITE -> "INTEGER PRIMARY KEY AUTOINCREMENT";
            case MYSQL, MARIADB -> "BIGINT AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "BIGSERIAL PRIMARY KEY";
            case H2, UNKNOWN -> "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";
        };
    }

    public static String varchar(int length) {
        if (length < 1 || length > 65535) throw new IllegalArgumentException("Invalid VARCHAR length: " + length);
        return "VARCHAR(" + length + ")";
    }

    public static void createIndexIfMissing(Connection connection, String indexName,
                                            String tableName, String... columns) throws SQLException {
        createIndexIfMissing(connection, false, indexName, tableName, columns);
    }

    public static void createUniqueIndexIfMissing(Connection connection, String indexName,
                                                  String tableName, String... columns) throws SQLException {
        createIndexIfMissing(connection, true, indexName, tableName, columns);
    }

    private static void createIndexIfMissing(Connection connection, boolean unique, String indexName,
                                             String tableName, String... columns) throws SQLException {
        Objects.requireNonNull(connection, "connection");
        DatabaseDialect dialect = detect(connection);
        if ((dialect == DatabaseDialect.MYSQL || dialect == DatabaseDialect.MARIADB)
                && indexExists(connection, tableName, indexName)) {
            return;
        }
        try (Statement statement = connection.createStatement()) {
            try {
                statement.execute(createIndexSql(dialect, unique, indexName, tableName, columns));
            } catch (SQLException failure) {
                if ((dialect == DatabaseDialect.MYSQL || dialect == DatabaseDialect.MARIADB)
                        && (failure.getErrorCode() == 1061 || indexExists(connection, tableName, indexName))) {
                    return;
                }
                throw failure;
            }
        }
    }

    public static void addColumnIfMissing(Connection connection, String tableName, String columnName,
                                          String columnDefinition) throws SQLException {
        requireIdentifier(tableName);
        requireIdentifier(columnName);
        Objects.requireNonNull(columnDefinition, "columnDefinition");
        if (columnExists(connection, tableName, columnName)) return;
        try (Statement statement = connection.createStatement()) {
            try {
                statement.execute("ALTER TABLE " + tableName + " ADD COLUMN " + columnName + " " + columnDefinition);
            } catch (SQLException failure) {
                try {
                    if (columnExists(connection, tableName, columnName)) return;
                } catch (SQLException verificationFailure) {
                    failure.addSuppressed(verificationFailure);
                }
                throw failure;
            }
        }
    }

    public static void renameColumnIfPresent(Connection connection, String tableName, String oldColumnName,
                                             String newColumnName) throws SQLException {
        requireIdentifier(tableName);
        requireIdentifier(oldColumnName);
        requireIdentifier(newColumnName);
        if (!columnExists(connection, tableName, oldColumnName)
                || columnExists(connection, tableName, newColumnName)) {
            return;
        }
        DatabaseDialect dialect = detect(connection);
        String quotedOld = (dialect == DatabaseDialect.MYSQL || dialect == DatabaseDialect.MARIADB)
                ? "`" + oldColumnName + "`"
                : "\"" + oldColumnName + "\"";
        try (Statement statement = connection.createStatement()) {
            statement.executeUpdate("ALTER TABLE " + tableName + " RENAME COLUMN "
                    + quotedOld + " TO " + newColumnName);
        }
    }

    static String createIndexSql(DatabaseDialect dialect, String indexName,
                                 String tableName, String... columns) {
        return createIndexSql(dialect, false, indexName, tableName, columns);
    }

    static String createUniqueIndexSql(DatabaseDialect dialect, String indexName,
                                       String tableName, String... columns) {
        return createIndexSql(dialect, true, indexName, tableName, columns);
    }

    private static String createIndexSql(DatabaseDialect dialect, boolean unique, String indexName,
                                         String tableName, String... columns) {
        Objects.requireNonNull(dialect, "dialect");
        requireIdentifier(indexName);
        requireIdentifier(tableName);
        if (columns == null || columns.length == 0) {
            throw new IllegalArgumentException("At least one index column is required");
        }
        StringBuilder columnSql = new StringBuilder();
        for (String column : columns) {
            requireIdentifier(column);
            if (!columnSql.isEmpty()) columnSql.append(',');
            columnSql.append(column);
        }
        String ifMissing = dialect == DatabaseDialect.MYSQL || dialect == DatabaseDialect.MARIADB
                ? "" : " IF NOT EXISTS";
        return "CREATE " + (unique ? "UNIQUE " : "") + "INDEX" + ifMissing + " " + indexName
                + " ON " + tableName + "(" + columnSql + ")";
    }

    private static boolean columnExists(Connection connection, String tableName, String columnName)
            throws SQLException {
        requireIdentifier(tableName);
        requireIdentifier(columnName);
        try (Statement statement = connection.createStatement();
             ResultSet rows = statement.executeQuery("SELECT * FROM " + tableName + " WHERE 1=0")) {
            var metadata = rows.getMetaData();
            for (int index = 1; index <= metadata.getColumnCount(); index++) {
                if (columnName.equalsIgnoreCase(metadata.getColumnName(index))) return true;
            }
            return false;
        }
    }

    private static boolean indexExists(Connection connection, String tableName, String indexName)
            throws SQLException {
        requireIdentifier(tableName);
        requireIdentifier(indexName);
        DatabaseMetaData metadata = connection.getMetaData();
        String catalog = connection.getCatalog();
        String schema = connection.getSchema();
        Set<String> tableCandidates = new LinkedHashSet<>();
        tableCandidates.add(tableName);
        tableCandidates.add(tableName.toUpperCase(Locale.ROOT));
        tableCandidates.add(tableName.toLowerCase(Locale.ROOT));
        for (String candidate : tableCandidates) {
            try (ResultSet indexes = metadata.getIndexInfo(catalog, schema, candidate, false, false)) {
                while (indexes.next()) {
                    if (indexName.equalsIgnoreCase(indexes.getString("INDEX_NAME"))) return true;
                }
            }
        }
        return false;
    }

    private static void requireIdentifier(String identifier) {
        if (identifier == null || !IDENTIFIER.matcher(identifier).matches()) {
            throw new IllegalArgumentException("Unsafe SQL identifier: " + identifier);
        }
    }
}
